// Copyright (C) 2025 Interactive Brokers LLC. All rights reserved. This code is subject to the terms
// and conditions of the IB API Non-Commercial License or the IB API Commercial License, as applicable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: AccountSummaryEnd.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountSummaryEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReqId         *int32                 `protobuf:"varint,1,opt,name=reqId,proto3,oneof" json:"reqId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSummaryEnd) Reset() {
	*x = AccountSummaryEnd{}
	mi := &file_AccountSummaryEnd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSummaryEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSummaryEnd) ProtoMessage() {}

func (x *AccountSummaryEnd) ProtoReflect() protoreflect.Message {
	mi := &file_AccountSummaryEnd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSummaryEnd.ProtoReflect.Descriptor instead.
func (*AccountSummaryEnd) Descriptor() ([]byte, []int) {
	return file_AccountSummaryEnd_proto_rawDescGZIP(), []int{0}
}

func (x *AccountSummaryEnd) GetReqId() int32 {
	if x != nil && x.ReqId != nil {
		return *x.ReqId
	}
	return 0
}

var File_AccountSummaryEnd_proto protoreflect.FileDescriptor

const file_AccountSummaryEnd_proto_rawDesc = "" +
	"\n" +
	"\x17AccountSummaryEnd.proto\x12\bprotobuf\"8\n" +
	"\x11AccountSummaryEnd\x12\x19\n" +
	"\x05reqId\x18\x01 \x01(\x05H\x00R\x05reqId\x88\x01\x01B\b\n" +
	"\x06_reqIdBr\n" +
	"\fcom.protobufB\x16AccountSummaryEndProtoP\x01Z\n" +
	".;protobuf\xa2\x02\x03PXX\xaa\x02\bProtobuf\xca\x02\bProtobuf\xe2\x02\x14Protobuf\\GPBMetadata\xea\x02\bProtobufb\x06proto3"

var (
	file_AccountSummaryEnd_proto_rawDescOnce sync.Once
	file_AccountSummaryEnd_proto_rawDescData []byte
)

func file_AccountSummaryEnd_proto_rawDescGZIP() []byte {
	file_AccountSummaryEnd_proto_rawDescOnce.Do(func() {
		file_AccountSummaryEnd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AccountSummaryEnd_proto_rawDesc), len(file_AccountSummaryEnd_proto_rawDesc)))
	})
	return file_AccountSummaryEnd_proto_rawDescData
}

var file_AccountSummaryEnd_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AccountSummaryEnd_proto_goTypes = []any{
	(*AccountSummaryEnd)(nil), // 0: protobuf.AccountSummaryEnd
}
var file_AccountSummaryEnd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AccountSummaryEnd_proto_init() }
func file_AccountSummaryEnd_proto_init() {
	if File_AccountSummaryEnd_proto != nil {
		return
	}
	file_AccountSummaryEnd_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AccountSummaryEnd_proto_rawDesc), len(file_AccountSummaryEnd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AccountSummaryEnd_proto_goTypes,
		DependencyIndexes: file_AccountSummaryEnd_proto_depIdxs,
		MessageInfos:      file_AccountSummaryEnd_proto_msgTypes,
	}.Build()
	File_AccountSummaryEnd_proto = out.File
	file_AccountSummaryEnd_proto_goTypes = nil
	file_AccountSummaryEnd_proto_depIdxs = nil
}
